"use client";

import { useState, useMemo } from "react";
import { Activity, ActivityStatus } from "@/lib/types";
import { useActivities } from "@/hooks/useActivities";

import ActivityFilters from "@/components/ActivityFilters";
import ActivityTable from "@/components/ActivityTable";
import ActivityModal from "@/components/ActivityModal";
import { StatCard } from "@/components/StatCard";
import { Spinner } from "@/components/ui/spinner";
import StatCardsSkeleton from "@/components/StatCardsSkeleton";

const Page: React.FunctionComponent = () => {
  const [search, setSearch] = useState<string>("");
  const [statusFilter, setStatusFilter] = useState<"all" | ActivityStatus>(
    "all",
  );
  const [selectedActivity, setSelectedActivity] = useState<
    Activity | undefined
  >(undefined);

  const { data, isLoading, error } = useActivities();

  // Filter activities based on search + status
  const filteredActivities = useMemo(() => {
    if (!data) return [];

    return data.filter((activity) => {
      const matchesStatus =
        statusFilter === "all" || activity.status === statusFilter;
      const matchesSearch =
        activity.user.toLowerCase().includes(search.toLowerCase().trim()) ||
        activity.type.toLowerCase().includes(search.toLowerCase().trim());

      return matchesStatus && matchesSearch;
    });
  }, [data, search, statusFilter]);

  // Stats counts based on filtered data
  const totalActivities = filteredActivities.length;
  const successfulActivities = filteredActivities.filter(
    (a) => a.status === "success",
  ).length;
  const failedActivities = filteredActivities.filter(
    (a) => a.status === "failed",
  ).length;

  return (
    <section className="px-7 py-12 max-w-7xl mx-auto relative">
      <h1 className="text-4xl font-bold mb-4">AI Activity Dashboard</h1>
      <p className="text-xl text-gray-600 mb-10">
        Monitor activity generated by AI agents
      </p>

      {isLoading ? (
        <StatCardsSkeleton />
      ) : (
        // Stats Cards
        <div className="grid gap-6 mb-8 md:grid-cols-3">
          <StatCard title="Total Activities" value={totalActivities} />
          <StatCard
            title="Successful Activities"
            value={successfulActivities}
          />
          <StatCard title="Failed Activities" value={failedActivities} />
        </div>
      )}

      {/* Filters */}
      <ActivityFilters
        search={search}
        onSearchChange={setSearch}
        statusFilter={statusFilter}
        onStatusChange={setStatusFilter}
      />

      {/* ActivityTable Loading / Error states */}
      {isLoading && (
        <div className="flex justify-center items-center py-12">
          <Spinner className="size-7" />
        </div>
      )}
      {error && (
        <p className="text-center text-red-500 mt-6">
          Error loading activities.
        </p>
      )}

      {/* Activity Table or Empty State */}
      {!isLoading && !error && (
        <ActivityTable
          activities={filteredActivities}
          onRowClick={setSelectedActivity}
        />
      )}

      {/* Modal */}
      <ActivityModal
        activity={selectedActivity ?? null}
        onClose={() => setSelectedActivity(undefined)}
      />
    </section>
  );
};

export default Page;
